[workspace]
members = [
    "examples/*",
    "src/*",
    "src/lib/*",
    "src/riot-rs",
    "src/riot-rs-boards",
    "src/riot-rs-boards/lm3s6965evb",
    "src/riot-rs-boards/nrf52",
    "src/riot-rs-boards/nrf52840dk",
    "src/riot-rs-boards/nucleo-f401re",
    "src/riot-rs-chips",
    "src/riot-rs-macros"
]

exclude = ["src/lib"]

default-members = ["examples/hello-world"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"
repository = "https://github.com/future-proof-iot/riot-rs"

[workspace.dependencies]
cfg-if = { version = "1.0.0" }
cortex-m = { version = "0.7", default-features = false, features = [ "inline-asm" ] }
cortex-m-rt = { version = "0.7" }
cortex-m-semihosting = { version = "0.5" }
critical-section = { version = "1.1.2" }

embassy-executor = { version = "0.5", default-features = false }
embassy-net = { version = "0.4", default-features = false }
embassy-net-driver-channel = { version = "0.2.0", default-features = false }
embassy-nrf = { version = "0.1", default-features = false }
embassy-rp = { version = "0.1", default-features = false }
embassy-sync = { version = "0.5", default-features = false }
embassy-time = { version = "0.3", default-features = false }
embassy-usb = { version = "0.1", default-features = false }

esp-hal = { version = "0.15", git = "https://github.com/kaspar030/esp-hal", branch = "for-riot-rs-290224", default-features = false }
esp-println = { version = "0.9.0" }
esp-wifi = { git = "https://github.com/kaspar030/esp-wifi", branch = "update-esp-hal" }

linkme = { version = "0.3.21", features = ["used_linker"] }

riot-rs = { path = "src/riot-rs" }
riot-rs-rt = { path = "src/riot-rs-rt" }
riot-rs-runqueue = { path = "src/riot-rs-runqueue" }

const_panic = { version = "0.2.8", default_features = false }
heapless = { version = "0.8.0", default-features = false }
konst = { version = "0.3.8", default_features = false }
ld-memory = { version = "0.2.9" }
static_cell = { version = "2.0.0", features = [ "nightly" ] }

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = 1

[profile.release]
incremental = false
codegen-units = 1
debug = true
lto = false
opt-level = "s"

[profile.release.package.esp-wifi]
opt-level = 3

[patch.crates-io]
# these are patched to work with critical-section
nrf51-pac = { git = "https://github.com/kaspar030/nrf-pacs", branch = "riot-rs" }
nrf52832-pac = { git = "https://github.com/kaspar030/nrf-pacs", branch = "riot-rs" }
nrf52840-pac = { git = "https://github.com/kaspar030/nrf-pacs", branch = "riot-rs" }

# riot-rs embassy fork
embassy-executor = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs-140224" }
embassy-hal-internal = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs-140224" }
embassy-nrf = { git = "https://github.com/kaspar030/embassy", branch = "for-riot-rs-140224" }
