[package]
name = "riot-rs-embassy"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section.workspace = true
linkme.workspace = true
static_cell.workspace = true

embassy-executor = { workspace = true, features = ["nightly"] }
embassy-net = { workspace = true, optional = true, features = [ "dhcpv4", "medium-ethernet" ] }
embassy-net-driver-channel = { workspace = true, optional = true }
embassy-sync = { workspace = true }
embassy-time = { workspace = true, optional = true }
embassy-usb = { workspace = true, optional = true }

# always
riot-rs-core = { path = "../riot-rs-core", optional = true }
riot-rs-rt = { path = "../riot-rs-rt" }
riot-rs-utils = { path = "../riot-rs-utils" }

heapless = "0.8.0"

# rpi-pico-w cyw43
cyw43 = { version = "0.1.0", features = ["firmware-logs"], optional = true }
cyw43-pio = { version = "0.1.0", features = ["overclock"], optional = true }

[target.'cfg(context = "cortex-m")'.dependencies]
embassy-executor = { workspace = true, features = [
  "arch-cortex-m",
  "executor-interrupt",
] }

[target.'cfg(context = "nrf52")'.dependencies]
embassy-nrf = { workspace = true, features = [
  "time-driver-rtc1",
  "time",
  "unstable-pac",
  "rt",
] }

[target.'cfg(context = "nrf52832")'.dependencies]
embassy-nrf = { workspace = true, features = [
  "nrf52832",
] }

[target.'cfg(context = "nrf52840")'.dependencies]
embassy-nrf = { workspace = true, features = [
  "nrf52840",
] }

[target.'cfg(context = "rp2040")'.dependencies]
embassy-rp = { workspace = true, features = [
  "rt",
  "time-driver",
  "unstable-pac",
#  "unstable-traits",
] }

[target.'cfg(context = "esp")'.dependencies]
esp-hal = { workspace = true, features = [ "embassy", "embassy-executor-interrupt", "embassy-time-systick" ] }

[target.'cfg(context = "esp32c3")'.dependencies]
esp-hal = { workspace = true, features = [ "esp32c3", "rt", "vectored", "embassy-time-systick" ] }

[features]
time = ["dep:embassy-time", "embassy-executor/integrated-timers"]
usb = ["dep:embassy-usb"]
net = ["dep:embassy-net"]
usb_ethernet = ["usb", "net"]

wifi_cyw43 = ["dep:cyw43", "dep:cyw43-pio", "dep:embassy-net-driver-channel", "net"]

threading = ["dep:riot-rs-core"]
override-network-config = []
override-usb-config = []
