[package]
name = "riot-rs-rt"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"

[dependencies]
cfg-if.workspace = true
linkme.workspace = true
riot-rs-threads = { path = "../riot-rs-threads", optional = true }
riot-rs-utils = { path = "../riot-rs-utils" }
rtt-target = { version = "0.4.0", optional = true }

[target.'cfg(context = "cortex-m")'.dependencies]
cortex-m = { workspace = true, features = ["critical-section-single-core"] }
cortex-m-rt = { workspace = true }
cortex-m-semihosting = { workspace = true, optional = true }
portable-atomic = { version = "1.6.0", features = ["critical-section"] }

[target.'cfg(context = "esp")'.dependencies]
esp-hal = { workspace = true, default-features = false }
esp-println = { workspace = true, features = ["esp32c3"] }
portable-atomic = { version = "1.6.0", default-features = false, features = ["require-cas"] }

[features]
#default = ["threading"]
threading = ["dep:riot-rs-threads"]
debug-console = []
silent-panic = []

[dev-dependencies]
riot-rs-boards = { path = "../riot-rs-boards" }
