[package]
name = "riot-rs-rt"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
license.workspace = true
edition = "2021"

[lints]
workspace = true

[dependencies]
cfg-if.workspace = true
linkme.workspace = true
riot-rs-debug.workspace = true
riot-rs-threads = { path = "../riot-rs-threads", optional = true }
riot-rs-utils = { workspace = true }
rtt-target = { version = "0.5.0", optional = true }

[target.'cfg(context = "cortex-m")'.dependencies]
cortex-m = { workspace = true, features = ["critical-section-single-core"] }
cortex-m-rt = { workspace = true }

[target.'cfg(context = "rp2040")'.dependencies]
# Use critical-section to provide an atomic CAS implementation.
portable-atomic = { workspace = true, features = ["critical-section"] }

[target.'cfg(context = "esp")'.dependencies]
esp-hal = { workspace = true, default-features = false }
portable-atomic = { workspace = true }

[features]
#default = ["threading"]
threading = ["dep:riot-rs-threads"]

debug-console = ["riot-rs-debug/debug-console"]
executor-single-thread = []
silent-panic = []
_panic-handler = []

# internal
# These features are used by `build.rs`, which doesn't "see" context
# variables.
_esp32 = []
_esp32c3 = []
_esp32c6 = []
_esp32s3 = []

[dev-dependencies]
riot-rs-boards = { path = "../riot-rs-boards" }
