[package]
name = "testing"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
riot-rs = { path = "../../src/riot-rs" }
riot-rs-boards = { path = "../../src/riot-rs-boards" }

embassy-executor = { workspace = true, default-features = false }

[dev-dependencies]
embedded-test = { version = "0.4.0", default-features = false, features = [ "defmt", "embassy", "external-executor" ] }

[[test]]
name = "example_test"
harness = false
