[package]
name = "riot-rs-nrf"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
cfg-if = { workspace = true }
defmt = { workspace = true, optional = true }
embassy-embedded-hal = { workspace = true, optional = true }
embassy-executor = { workspace = true, default-features = false, features = [
  "arch-cortex-m",
] }
embassy-nrf = { workspace = true, default-features = false, features = [
  "time-driver-rtc1",
  "time",
  "unstable-pac",
  "rt",
] }
embedded-hal-async = { workspace = true }
embedded-storage-async = { workspace = true, optional = true }
paste = { workspace = true }
portable-atomic = { workspace = true }
riot-rs-debug = { workspace = true }
riot-rs-embassy-common = { workspace = true }
riot-rs-random = { workspace = true, optional = true }

[target.'cfg(context = "nrf52832")'.dependencies]
embassy-nrf = { workspace = true, features = ["nrf52832"] }

[target.'cfg(context = "nrf52833")'.dependencies]
# Disable NFC support for now, as we do not support it yet.
embassy-nrf = { workspace = true, features = ["nfc-pins-as-gpio", "nrf52833"] }

[target.'cfg(context = "nrf52840")'.dependencies]
embassy-nrf = { workspace = true, features = ["nrf52840"] }

[target.'cfg(context = "nrf5340")'.dependencies]
embassy-nrf = { workspace = true, features = ["nrf5340-app-s"] }

[features]
## Enables GPIO interrupt support.
external-interrupts = [
  "embassy-nrf/gpiote",
  "riot-rs-embassy-common/external-interrupts",
]

## Enables seeding the random number generator from hardware.
hwrng = ["dep:riot-rs-random"]

## Enables I2C support.
i2c = ["riot-rs-embassy-common/i2c", "embassy-executor/integrated-timers"]

## Enables SPI support.
spi = ["riot-rs-embassy-common/spi", "embassy-executor/integrated-timers"]
## Enables storage support.
storage = ["dep:embedded-storage-async", "dep:embassy-embedded-hal"]

## Enables USB support.
usb = []

## Enables defmt support.
defmt = ["dep:defmt", "embassy-nrf/defmt"]

## Enables the interrupt executor.
executor-interrupt = ["embassy-executor/executor-interrupt"]
