[package]
name = "espressif-esp32-wroom-32"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
riot-rs-rt = { workspace = true, features = ["_esp32"] }
riot-rs-debug = { workspace = true }
